parameters:
    pim_connector.processor.denormalization.product.class:             Balance\Component\Connector\Processor\Denormalization\ProductProcessor
    pim_connector.processor.denormalization.product_association.class: Balance\Component\Connector\Processor\Denormalization\ProductAssociationProcessor

services:
    pim_connector.processor.denormalization.product.flat:
        class: %pim_connector.processor.denormalization.product.class%
        arguments:
            - '@pim_connector.array_converter.flat.product'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.builder.product'
            - '@pim_catalog.updater.product'
            - '@pim_catalog.validator.product'
            - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@pim_catalog.comparator.filter.product'
            - '@pim_catalog.localization.localizer.converter'
            - '@session'